version: 2

updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "18:07"
      timezone: "Europe/London"
    groups:
      non-breaking:
        update-types:
          - 'minor'
          - 'patch'
